# This is a basic workflow to help you get started with Actions

name: CI-data-spider

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  grab_2018:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./data-spider

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Restore dependencies
        run: |
          pip install -r requirements.txt
      - name: Execute
        run: |
          ./run.sh 2018

      - name: Archive the result
        uses: actions/upload-artifact@v2
        with:
          name: result_2018.csv
          path: |
            ./data-spider/result.csv
  # This workflow contains a single job called "build"
  grab_2019:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./data-spider

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Restore dependencies
        run: |
          pip install -r requirements.txt
      - name: Execute
        run: |
          ./run.sh 2019

      - name: Archive the result
        uses: actions/upload-artifact@v2
        with:
          name: result_2019.csv
          path: |
            ./data-spider/result_2019.csv
  # This workflow contains a single job called "build"
  grab_2020:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./data-spider

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Restore dependencies
        run: |
          pip install -r requirements.txt
      - name: Execute
        run: |
          ./run.sh 2020

      - name: Archive the result
        uses: actions/upload-artifact@v2
        with:
          name: result_2020.csv
          path: |
            ./data-spider/result_2020.csv
              # This workflow contains a single job called "build"
  grab_2021:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./data-spider

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Restore dependencies
        run: |
          pip install -r requirements.txt
      - name: Execute
        run: |
          ./run.sh 2021

      - name: Archive the result
        uses: actions/upload-artifact@v2
        with:
          name: result_2021.csv
          path: |
            ./data-spider/result_2021.csv